-- AlterTable
ALTER TABLE "public"."plans" 
DROP COLUMN IF EXISTS "name",
DROP COLUMN IF EXISTS "description",
DROP COLUMN IF EXISTS "dataAmount",
DROP COLUMN IF EXISTS "duration",
DROP COLUMN IF EXISTS "countries",
DROP COLUMN IF EXISTS "originalPrice",
ADD COLUMN IF NOT EXISTS "type" TEXT,
ADD COLUMN IF NOT EXISTS "planCategory" TEXT,
ADD COLUMN IF NOT EXISTS "locationName" TEXT,
ADD COLUMN IF NOT EXISTS "planName" TEXT,
ADD COLUMN IF NOT EXISTS "gbs" DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS "days" INTEGER,
ADD COLUMN IF NOT EXISTS "preActivationDays" INTEGER,
ADD COLUMN IF NOT EXISTS "sms" TEXT,
ADD COLUMN IF NOT EXISTS "reloadable" TEXT,
ADD COLUMN IF NOT EXISTS "operators" TEXT,
ADD COLUMN IF NOT EXISTS "countryCodes" TEXT,
ADD COLUMN IF NOT EXISTS "slug" TEXT,
ADD COLUMN IF NOT EXISTS "planId" TEXT,
ADD COLUMN IF NOT EXISTS "proposedPriceUsd" DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS "country" TEXT,
ADD COLUMN IF NOT EXISTS "ourCost" DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS "appliedMarkupPct" DECIMAL(5,2);

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "plans_slug_key" ON "public"."plans"("slug");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "plans_planId_key" ON "public"."plans"("planId");
